name: smart-price-tracker
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - requests
  - pandas
  - pip
  - pip:
      - delta-spark==3.2.0
      - pyspark==3.5
      - pytest
      - packaging
      - beautifulsoup4
      - selenium
      - webdriver-manager
      - python-dotenv
