name: smart-price-tracker
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - requests
  - pandas
  - pyspark
  - pip
  - pip:
      - delta-spark=3.2.0
      - pytest
      - packaging
      - beautifulsoup4
      -pandas
