azure:
  account_name: "smartpricetrackerstorage"
  access_key: "OwdwKueskwEZli7MrM1cz274lHsRYYuF6W2gIZDZdJgFM70Jchli203dRK7iw+sJpmuweAz/MPVh+AStL0ISWw=="
  container_name: "smart-price-container"
  
  raw_path: "Data/raw"
  processed_path: "Data/processed/processed_data"
  delta_path: "Data/delta_data/curated_data"


spark:
  app_name: "SmartPriceTrackerPipeline"
  master: "local[*]" # Use all local cores for development

