azure:
  account_name: "smartpricetrackerstorage"
  access_key: ""
  container_name: "smart-price-container"
  
  raw_path: "Data/raw"
  processed_path: "Data/processed/processed_data"
  delta_path: "Data/delta_data/curated_data"


spark:
  app_name: "SmartPriceTrackerPipeline"
  master: "local[*]" # Use all local cores for development

