azure:
  # The name of your Azure Storage Account (e.g., 'prcetracker01')
  account_name: "smartpricetrackerstorage" 
  
  # The name of your Azure container/filesystem (e.g., 'price-data-container')
  # This acts as the root of your data lake.
  container_name: "smart-price-container"
  
  raw_path: "Data/raw"
  processed_path: "Data/processed"
  delta_path: "Data/delta_data"


spark:
  app_name: "SmartPriceTrackerPipeline"
  master: "local[*]" # Use all local cores for development

